export { default as BlinkIcon } from './Blink'
export { default as DiscordIcon } from './Discord'
export { default as MediumIcon } from './Medium'
export { default as TwitterIcon } from './Twitter'
export { default as TelegramIcon } from './Telegram'